package com.example.equa_notepad_plats.data.remote.mappers

import com.example.equa_notepad_plats.data.local.entities.BookEntity
import com.example.equa_notepad_plats.data.local.entities.FormulaEntity
import com.example.equa_notepad_plats.data.local.entities.UserEntity
import com.example.equa_notepad_plats.data.remote.models.RemoteBook
import com.example.equa_notepad_plats.data.remote.models.RemoteFormula
import com.example.equa_notepad_plats.data.remote.models.RemoteUser
import java.text.SimpleDateFormat
import java.util.*

// ==================== LOCAL TO REMOTE ====================

fun UserEntity.toRemote(): RemoteUser {
    return RemoteUser(
        id = id,
        name = name,
        email = email,
        photoUrl = photoUrl
    )
}

fun BookEntity.toRemote(userId: String, remoteId: String? = null): RemoteBook {
    return RemoteBook(
        id = remoteId,
        userId = userId,
        name = name,
        description = description,
        imageUri = imageUri,
        createdAt = formatTimestampToISO(createdAt),
        updatedAt = formatTimestampToISO(System.currentTimeMillis()),
        isDeleted = false
    )
}

fun FormulaEntity.toRemote(
    userId: String,
    remoteBookId: String,
    remoteId: String? = null
): RemoteFormula {
    return RemoteFormula(
        id = remoteId,
        bookId = remoteBookId,
        userId = userId,
        name = name,
        formulaText = formulaText,
        description = description,
        imageUri = imageUri,
        createdAt = formatTimestampToISO(createdAt),
        updatedAt = formatTimestampToISO(System.currentTimeMillis()),
        isDeleted = false
    )
}

// ==================== REMOTE TO LOCAL ====================

fun RemoteUser.toLocal(): UserEntity {
    return UserEntity(
        id = id,
        name = name,
        email = email,
        photoUrl = photoUrl,
        isGuest = false
    )
}

fun RemoteBook.toLocal(): BookEntity {
    return BookEntity(
        id = 0, // Will be auto-generated by Room
        name = name,
        description = description,
        imageUri = imageUri,
        createdAt = parseISOToTimestamp(createdAt) ?: System.currentTimeMillis()
    )
}

fun RemoteFormula.toLocal(localBookId: Int): FormulaEntity {
    return FormulaEntity(
        id = 0, // Will be auto-generated by Room
        bookId = localBookId,
        name = name,
        formulaText = formulaText,
        description = description,
        imageUri = imageUri,
        createdAt = parseISOToTimestamp(createdAt) ?: System.currentTimeMillis()
    )
}

// ==================== HELPER FUNCTIONS ====================

/**
 * Converts a timestamp (milliseconds) to ISO 8601 format for Supabase
 * Example: 2024-01-15T10:30:00Z
 */
private fun formatTimestampToISO(timestamp: Long): String {
    val sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US)
    sdf.timeZone = TimeZone.getTimeZone("UTC")
    return sdf.format(Date(timestamp))
}

/**
 * Converts ISO 8601 string to timestamp (milliseconds)
 */
private fun parseISOToTimestamp(isoString: String?): Long? {
    if (isoString == null) return null

    return try {
        val sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.US)
        sdf.timeZone = TimeZone.getTimeZone("UTC")

        // Remove 'Z' or timezone info if present
        val cleanString = isoString.replace("Z", "").substringBefore("+").substringBefore("-")
        sdf.parse(cleanString)?.time
    } catch (e: Exception) {
        null
    }
}